name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 

      - uses: Platane/snk@v3 
        id: snake_gif
        with:
          github_user_name: EmillyAndradeDev 
          outputs: |
            ./github-snake.svg
            ./github-snake-dark.svg?palette=github-dark
            
      - uses: EndBug/add-and-commit@v9 
        with:
          branch: main
          message: "docs: update snake animation"
          add: "github-snake.svg github-snake-dark.svg"